import type { Metadata } from "next";
import { LocalStorageProvider } from '@context/LocalStorageContext';
import { SidebarProvider } from '@context/SidebarContext';
import "./globals.css";

export const metadata: Metadata = {
  title: "test Admin App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* text-base md:text-xs lg:text-sm */}
      <body className="antialiased">
        <LocalStorageProvider>
          <SidebarProvider>
            {children}
          </SidebarProvider>
        </LocalStorageProvider>
      </body>
    </html>
  );
}
